import Image from "next/image";

export const metadata = {
  title: "About страница",
  description: "Generated by create next app About страница",
};

export default function About() {
  return (
    <section className="content">
      <h2 className="section-title">Изучаем Next JS </h2>
      <Image className="mx-auto shadow-sm" src="/dodge-400-200.jpg" alt="Dodge" width={400} height={200} loading="eager"/>
    </section>
  );
}
