import Header from "@components/Header";
import Footer from "@components/Footer";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin","cyrillic"],
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
  display:'swap' // текст зразу показується (системним шрифтом)
  ,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${roboto.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <div className="bg-grid"></div>
        <Header />
        <main className='container page'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
